In [29]:
cd "Trabajo 1"

[WinError 2] The system cannot find the file specified: 'Trabajo 1'
c:\Users\etien\OneDrive\Documentos\Ramos\Inteligencia de negocios\Trabajo 1


In [30]:
import pandas as pd
import numpy as np

df = pd.read_csv("train.csv", header=None)
df.head(5)

0        1         2        3        4       5
0  44.0380  7.71640  42.49700   6.2617  1.00860  3.3859
1  -8.4255  0.87524  -1.41120  -5.2240  1.24650  4.3779
2 -18.6710  0.99898  -4.35750  -6.2929  0.22110  4.4969
3  45.2560  8.49280  50.61900   3.9974  1.83330  3.4199
4 -12.7770  2.06560   0.22661 -10.6520 -0.60333  4.2499

In [31]:
df_sh = df.sample(frac=1).reset_index(drop=True) # Reordenar valores aleatoriamente.
df_sh.head(5)


0        1        2        3        4       5
0 -11.4830   3.3142  -6.3201  -4.6073 -0.40540  4.2429
1 -36.3550  -1.0219   2.5028   3.9395  0.24795  5.1059
2   7.0099   2.5101   1.8744 -16.0860 -1.02110  4.1769
3  -2.6432   1.4265  -7.7622 -10.2160  0.59493  4.4289
4  48.7510  14.2430  56.7570   4.9347  1.27880  3.2559

In [32]:
df_sh.columns

Int64Index([0, 1, 2, 3, 4, 5], dtype='int64')

In [33]:
Xe = df_sh.drop(labels=[5], axis=1)
Xe.head(5)

0        1        2        3        4
0 -11.4830   3.3142  -6.3201  -4.6073 -0.40540
1 -36.3550  -1.0219   2.5028   3.9395  0.24795
2   7.0099   2.5101   1.8744 -16.0860 -1.02110
3  -2.6432   1.4265  -7.7622 -10.2160  0.59493
4  48.7510  14.2430  56.7570   4.9347  1.27880

In [34]:
Ye = df_sh[5]
Ye.head(5)

0    4.2429
1    5.1059
2    4.1769
3    4.4289
4    3.2559
Name: 5, dtype: float64

In [35]:
Xe.to_numpy()

array([[-11.483  ,   3.3142 ,  -6.3201 ,  -4.6073 ,  -0.4054 ],
       [-36.355  ,  -1.0219 ,   2.5028 ,   3.9395 ,   0.24795],
       [  7.0099 ,   2.5101 ,   1.8744 , -16.086  ,  -1.0211 ],
       ...,
       [-53.525  ,  -2.955  ,   2.4854 ,   6.4745 ,   0.68666],
       [ -1.7051 ,   3.1361 ,  -1.0943 ,  -6.4069 ,  -1.3492 ],
       [  3.3097 ,   3.0777 , -14.797  ,   4.1791 ,   0.08197]])

In [36]:
Ye.min()

1.6459

In [37]:
Ye.max()

5.5959

In [38]:
Xe.mean()

0   -8.585263
1    1.917864
2    2.113191
3   -0.360373
4   -0.029521
dtype: float64

In [91]:
def normalize(df):
    a = 0.01
    b = 0.99
    df_norm = pd.DataFrame()

    for col in df:
        min_ = df[col].min()
        max_ = df[col].max()

        df_norm[col] = (df[col] - min_) * (b - a) / (max_ - min_) + a

    return df_norm

normalize(Xe).head()

0         1         2         3         4
0  0.354211  0.371222  0.440358  0.498136  0.404415
1  0.165359  0.208806  0.491919  0.675572  0.486258
2  0.494627  0.341103  0.488247  0.259832  0.327288
3  0.421332  0.300515  0.431931  0.381696  0.529723
4  0.811566  0.780579  0.808982  0.696233  0.615390

In [80]:
Xe

0         1         2         3         4
0   -11.4830   3.31420  -6.32010  -4.60730 -0.405400
1   -36.3550  -1.02190   2.50280   3.93950  0.247950
2     7.0099   2.51010   1.87440 -16.08600 -1.021100
3    -2.6432   1.42650  -7.76220 -10.21600  0.594930
4    48.7510  14.24300  56.75700   4.93470  1.278800
..       ...       ...       ...       ...       ...
370 -34.6230  -0.99762   0.31463   0.36829  0.483540
371 -18.2390   1.73250   0.47259  -4.81530  0.036221
372 -53.5250  -2.95500   2.48540   6.47450  0.686660
373  -1.7051   3.13610  -1.09430  -6.40690 -1.349200
374   3.3097   3.07770 -14.79700   4.17910  0.081970

[375 rows x 5 columns]

In [82]:
Ye

0      4.2429
1      5.1059
2      4.1769
3      4.4289
4      3.2559
        ...  
370    4.8039
371    4.1769
372    5.4899
373    3.5949
374    3.9929
Name: 5, Length: 375, dtype: float64

In [59]:
nodes = 20
x = 5
w1 = [ [ np.random.random() for n in range(nodes) ] for i in range(x) ]
len(w1[0])

20

In [166]:
w1 = np.random.random((nodes, x))
w2 = np.random.random((1, nodes)) #dim -> (1x20)

In [173]:
def act_sigmoid(z):
    return(1/(1+np.exp(-z))) 

In [72]:
normalize(Xe).loc[0]

0    0.354211
1    0.371222
2    0.440358
3    0.498136
4    0.404415
Name: 0, dtype: float64

In [78]:
np.dot(w1, normalize(Xe).loc[0]) # (20x5) * ()

array([0.85163956, 0.61342143, 0.85006823, 1.01549225, 0.82765382,
       0.73086046, 1.07533939, 0.4326841 , 0.69703258, 0.90493186,
       0.89291201, 1.53194783, 0.73238853, 1.29304201, 0.83665627,
       0.66836265, 1.08109468, 1.49477048, 1.12666439, 1.10295486])

In [125]:
normalize(Xe).to_numpy().transpose().shape

(5, 375)

In [127]:
np.dot(w1, normalize(Xe).to_numpy().transpose()).shape

(20, 375)

In [120]:
normalize(df).drop(labels=[i for i in range(5)],axis = 1)

5
0    0.441696
1    0.687813
2    0.717337
3    0.450132
4    0.656056
..        ...
370  0.477919
371  0.801691
372  0.162582
373  0.796729
374  0.603210

[375 rows x 1 columns]

In [137]:
def norm(df):
    a = 0.01
    b = 0.99
    df_norm = pd.DataFrame()

    for col in df:
        min_ = df[col].min()
        max_ = df[col].max()

        df_norm[col] = (df[col] - min_) * (b - a) / (max_ - min_) + a
    
    x = df_norm.drop(labels=[5], axis=1)
    y = df_norm.drop(labels=[i for i in range(5)],axis = 1)

    return (x.to_numpy(),y.to_numpy())

In [159]:
Xe, Ye = norm(df)
Xe.T.shape

(5, 375)

In [167]:
z1 = np.dot(w1, Xe.T )
z1

array([[2.37690185, 1.63631982, 1.42020673, ..., 1.72400143, 1.48540359,
        1.66838797],
       [1.89210065, 1.36270849, 1.21703283, ..., 1.50880459, 1.33028148,
        1.38501654],
       [1.35261476, 0.77046836, 0.71719566, ..., 1.35097671, 0.68335197,
        0.8952246 ],
       ...,
       [1.75126985, 1.05338134, 0.98633523, ..., 1.73270613, 1.09039982,
        1.14545251],
       [1.684781  , 1.01680094, 0.95159125, ..., 1.42733079, 0.95022923,
        1.13996531],
       [1.02348671, 0.78741904, 0.69959984, ..., 0.99973505, 0.82823402,
        0.76980307]])

In [175]:
z2 = np.dot(w2, act_sigmoid(z1))
act_sigmoid(z2)

array([[0.99987849],
       [0.99967576],
       [0.99959504],
       [0.99988891],
       [0.99957432],
       [0.99973168],
       [0.99966967],
       [0.99959518],
       [0.9996119 ],
       [0.99962804],
       [0.99960893],
       [0.99963849],
       [0.99961924],
       [0.99963506],
       [0.99954237],
       [0.99957671],
       [0.99958994],
       [0.99971549],
       [0.99960286],
       [0.99967799],
       [0.99991381],
       [0.99966075],
       [0.99952622],
       [0.99958663],
       [0.99970592],
       [0.99967301],
       [0.99984784],
       [0.99957843],
       [0.9996357 ],
       [0.99962296],
       [0.99959653],
       [0.99959451],
       [0.99973207],
       [0.99959667],
       [0.99991526],
       [0.99960202],
       [0.99958037],
       [0.99965306],
       [0.99955813],
       [0.99957669],
       [0.99990371],
       [0.99983089],
       [0.99959119],
       [0.99967021],
       [0.99957789],
       [0.9996161 ],
       [0.99985257],
       [0.999

In [176]:
Ye

array([[0.4416962 ],
       [0.68781266],
       [0.71733671],
       [0.45013165],
       [0.6560557 ],
       [0.6962481 ],
       [0.64588354],
       [0.73842532],
       [0.79077468],
       [0.49354937],
       [0.77340759],
       [0.68533165],
       [0.81508861],
       [0.64042532],
       [0.96891139],
       [0.91829873],
       [0.77092658],
       [0.67764051],
       [0.78878987],
       [0.55036456],
       [0.45856709],
       [0.64017722],
       [0.98702278],
       [0.53696709],
       [0.37173165],
       [0.73916962],
       [0.01      ],
       [0.85825823],
       [0.76794937],
       [0.77117468],
       [0.83022278],
       [0.80268354],
       [0.54589873],
       [0.62504304],
       [0.15737215],
       [0.88703797],
       [0.82451646],
       [0.72924557],
       [0.94484557],
       [0.85726582],
       [0.34419241],
       [0.27918987],
       [0.73644051],
       [0.60767595],
       [0.66101772],
       [0.63099747],
       [0.21344304],
       [0.260